version: "3.5"

services: 
  backend:
    container_name: backend
    image: "omnistack:v01"
    ports: 
      - 81:3333
    volumes: 
      - ${PWD}/backend:/opt/ui
    command: yarn dev
  frontend:
    container_name: frontend
    image: "omnistack:v01"
    ports:
      - 80:3000
    volumes: 
      - ${PWD}/web:/opt/ui
    command: yarn start
  expo:
    container_name: expo-android
    image: "omnistack:v01"
    env_file: .env
    ports: 
      - 19000:19000
      - 19001:19001
      - 19002:19002
      - 19006:19006
    volumes:
      - ${PWD}/mobile:/opt/ui
    command: yarn start
